### ISSUE TITLE
non-manual marker window not working

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#328]
When trying to enter non-manuals, you can select any non-manual and the blue check will appear but when clicking DONE nothing happens. The window is frozen. I can click an unclick other non-manuals but the DONE button doesn't work so I have to close out SS and reopen it and then it works. This has happened about five times. 

![Screen Shot 2020-02-13 at 12 12 34 PM](https://user-images.githubusercontent.com/38887034/74474489-75e22700-4e5a-11ea-8b81-b88aa35ae9d5.png)

**Comment by bugspotter33** [comment]
This is still an issue with the latest version of SS. I am currently working on file TG 121418 U6

**Comment by gregorydimitriadis** [comment]
@bugspotter33 indeed, this issue was not addressed in the latest release.

**Comment by bugspotter33** [comment]
Updating an entry, the correct file number is TG 012418

**Comment by bugspotter33** [comment]
issue occurred again in LB flie 122818 U23

**Comment by bugspotter33** [comment]
This is still an issue. Working on file Ben Control of Sound 2.6 U17

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The field selector has been reworked.  This issue is believed to have been resolved.

Closing.  If experiencing issue again, open new issue.
